plugins {
    id 'dev.gradleplugins.java-gradle-plugin'
    id 'dev.gradleplugins.gradle-plugin-unit-test'
}

gradlePlugin {
    plugins {
        enterprise {
            id = 'nokeebuild.enterprise'
            implementationClass = 'nokeebuild.enterprise.DevelocityPlugin'
        }
    }

    dependencies {
        runtimeOnly project(':build-cache')
        runtimeOnly project(':build-scan')
		runtimeOnly 'com.gradle:develocity-gradle-plugin'
		runtimeOnly 'com.gradle:common-custom-user-data-gradle-plugin'
    }
}
