description: Run Gradle with Nokee cache
name: Gradle
inputs:
    arguments:
        description: 'Gradle arguments'
        required: true
    github-token:
        description: 'GitHub token'
        required: true
    build-scan-access-key:
        description: 'Build cache access key'
        required: true
runs:
    using: composite
    steps:
        -   uses: actions/setup-java@v3
            with:
                distribution: temurin
                java-version: 8
        -   name: Set up OSS Community Develocity Instance for Gradle
            uses: gradle/actions/setup-gradle@v6.2.0
            with:
                develocity-access-key: ${{ inputs.build-scan-access-key }}
        -   name: Run Gradle
            run: ./gradlew ${{ inputs.arguments }} --no-daemon --continue
            shell: bash
